name: Female-Gender-Mod-Paper
version: '${version}'
main: dbrighthd.wildfiregendermodplugin.GenderModPlugin
api-version: '26.2'
description: Paper 26.3; supports Female Gender Mod Beta.4 protocol 1 and 5.0.0 protocol 2
authors: [EllanStudio]